trigger:
  - lithium

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install -yy docker.io && sudo systemctl start docker
  displayName: 'InstallDocker'
- script: |
    ./docker-build.sh
  displayName: 'BuildAmd64'
- script: |
    env USE_I386=1 ./docker-build.sh
  displayName: 'BuildI386'
- task: CopyFiles@2
  inputs:
    Contents: 'build/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'debian'
