trigger:
  - lithium

pool: 'Default'

steps:
- script: |
    ./docker-build.sh
  displayName: 'BuildAmd64'
- task: CopyFiles@2
  inputs:
    Contents: 'build/amd64/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- script: |
    env USE_I386=1 ./docker-build.sh
  displayName: 'BuildI386'
- task: CopyFiles@2
  inputs:
    Contents: 'build/i386/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'debian'
